# Generated by Django 5.1.1 on 2024-09-07 14:23

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_snapshot', models.JSONField(default=dict)),
                (
                    'quantity_sold',
                    models.PositiveIntegerField(default=0, verbose_name='quantity sold'),
                ),
                (
                    'total_sales_amount',
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='total sales amount',
                    ),
                ),
                (
                    'date_of_sale',
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name='date of sale'
                    ),
                ),
                (
                    'product',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='products.product',
                        verbose_name='product',
                    ),
                ),
            ],
            options={
                'verbose_name': 'sales record',
                'verbose_name_plural': 'sales records',
                'indexes': [
                    models.Index(fields=['uuid'], name='sales_sales_uuid_27315f_idx'),
                    models.Index(fields=['date_of_sale'], name='sales_sales_date_of_7c5a5c_idx'),
                ],
            },
        ),
    ]
