# Generated by Django 5.1.1 on 2024-09-08 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_populate_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrecord',
            name='quantity_sold',
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='quantity sold',
            ),
        ),
    ]
