# Generated by Django 5.1.1 on 2024-09-07 14:23

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                (
                    'category',
                    models.CharField(
                        blank=True, default='', max_length=255, verbose_name='category'
                    ),
                ),
                (
                    'price',
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=19,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='price',
                    ),
                ),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'indexes': [
                    models.Index(fields=['uuid'], name='products_pr_uuid_245271_idx'),
                    models.Index(fields=['category'], name='products_pr_categor_14b9c0_idx'),
                ],
            },
        ),
    ]
